routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['uses' => 'GeneralController@index', 'as' => 'app']);
Route::get('/home', ['uses' => 'GeneralController@index', 'as' => 'home']);

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
	Route::get('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'auth.logout']);

	/***********************************************************************************************************************************************
	 * Authenticated Routes for Admin Access
	 */
	Route::group(['middleware' => 'admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function(){

		Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);

		Route::group(['prefix' => 'client'], function(){
			Route::get('/', ['uses' => 'ClientController@index', 'as' => 'clients']);
			Route::get('create', ['uses' => 'ClientController@create', 'as' => 'clients.create']);
			Route::post('create', ['uses' => 'ClientController@store', 'as' => 'clients.store']);
			Route::get('{client}/edit', ['uses' => 'ClientController@edit', 'as' => 'clients.edit']);
			Route::put('{client}/edit', ['uses' => 'ClientController@update', 'as' => 'clients.update']);
			Route::get('{client}/delete', ['uses' => 'ClientController@delete', 'as' => 'clients.delete']);

			Route::group(['prefix' => '{client}', 'as' => 'clients.'], function(){

			    Route::group(['prefix' => 'users'], function(){
                    Route::get('', ['uses' => 'ClientUserController@index', 'as' => 'users']);
                    Route::get('create', ['uses' => 'ClientUserController@create', 'as' => 'users.create']);
                    Route::post('create', ['uses' => 'ClientUserController@store', 'as' => 'users.store']);
                    Route::get('{user}/edit', ['uses' => 'ClientUserController@edit', 'as' => 'users.edit']);
                    Route::put('{user}/edit', ['uses' => 'ClientUserController@update', 'as' => 'users.update']);
                    Route::get('{user}/delete', ['uses' => 'ClientUserController@delete', 'as' => 'users.delete']);
                });

				Route::group(['prefix' => 'roles'], function(){
                    Route::get('', ['uses' => 'ClientRoleController@index', 'as' => 'roles']);
                    Route::get('create', ['uses' => 'ClientRoleController@create', 'as' => 'roles.create']);
                    Route::post('create', ['uses' => 'ClientRoleController@store', 'as' => 'roles.store']);
                    Route::get('{role}/edit', ['uses' => 'ClientRoleController@edit', 'as' => 'roles.edit']);
                    Route::put('{role}/edit', ['uses' => 'ClientRoleController@update', 'as' => 'roles.update']);
                    Route::get('{role}/delete', ['uses' => 'ClientRoleController@delete', 'as' => 'roles.delete']);
                });

				Route::get('branch', ['uses' => 'ClientBranchController@index', 'as' => 'branches']);
				Route::get('branch/create', ['uses' => 'ClientBranchController@create', 'as' => 'branches.create']);
				Route::post('branch/create', ['uses' => 'ClientBranchController@store', 'as' => 'branches.store']);
				Route::get('branch/{branch}/edit', ['uses' => 'ClientBranchController@edit', 'as' => 'branches.edit']);
				Route::put('branch/{branch}/edit', ['uses' => 'ClientBranchController@update', 'as' => 'branches.update']);
				Route::get('branch/{branch}/delete', ['uses' => 'ClientBranchController@delete', 'as' => 'branches.delete']);

                Route::group(['prefix' => 'items'], function(){

                    Route::group(['prefix' => 'categories', 'as' => 'items.'], function(){
                        Route::get('', ['uses' => 'ClientItemsCategoryController@index', 'as' => 'categories']);
                        Route::get('create', ['uses' => 'ClientItemsCategoryController@create', 'as' => 'categories.create']);
                        Route::post('create', ['uses' => 'ClientItemsCategoryController@store', 'as' => 'categories.store']);
                        Route::get('{category}/edit', ['uses' => 'ClientItemsCategoryController@edit', 'as' => 'categories.edit']);
                        Route::put('{category}/edit', ['uses' => 'ClientItemsCategoryController@update', 'as' => 'categories.update']);
                        Route::get('{category}/delete', ['uses' => 'ClientItemsCategoryController@delete', 'as' => 'categories.delete']);
                    });

                    Route::get('', ['uses' => 'ClientItemsController@index', 'as' => 'items']);
                    Route::get('create', ['uses' => 'ClientItemsController@create', 'as' => 'items.create']);
                    Route::post('create', ['uses' => 'ClientItemsController@store', 'as' => 'items.store']);
                    Route::get('{item}/edit', ['uses' => 'ClientItemsController@edit', 'as' => 'items.edit']);
                    Route::put('{item}/edit', ['uses' => 'ClientItemsController@update', 'as' => 'items.update']);
                    Route::get('{item}/delete', ['uses' => 'ClientItemsController@delete', 'as' => 'items.delete']);

                    Route::get('generate-variations', ['uses' => 'ClientItemsController@generateVariations', 'as' => 'items.generate-variations']);
                });

				Route::get('employees', ['uses' => 'ClientEmployeesController@index', 'as' => 'employees']);
				Route::get('employees/create', ['uses' => 'ClientEmployeesController@create', 'as' => 'employees.create']);
				Route::post('employees/create', ['uses' => 'ClientEmployeesController@store', 'as' => 'employees.store']);
				Route::get('employees/{employee}/edit', ['uses' => 'ClientEmployeesController@edit', 'as' => 'employees.edit']);
				Route::put('employees/{employee}/edit', ['uses' => 'ClientEmployeesController@update', 'as' => 'employees.update']);
				Route::get('employees/{employee}/delete', ['uses' => 'ClientEmployeesController@delete', 'as' => 'employees.delete']);

                Route::get('customers', ['uses' => 'ClientCustomerController@index', 'as' => 'customers']);
                Route::get('customers/create', ['uses' => 'ClientCustomerController@create', 'as' => 'customers.create']);
                Route::post('customers/create', ['uses' => 'ClientCustomerController@store', 'as' => 'customers.store']);
                Route::get('customers/{customer}/edit', ['uses' => 'ClientCustomerController@edit', 'as' => 'customers.edit']);
                Route::put('customers/{customer}/edit', ['uses' => 'ClientCustomerController@update', 'as' => 'customers.update']);
                Route::get('customers/{customer}/delete', ['uses' => 'ClientCustomerController@delete', 'as' => 'customers.delete']);

                Route::get('attributes', ['uses' => 'ClientAttributeController@index', 'as' => 'attributes']);
                Route::get('attributes/create', ['uses' => 'ClientAttributeController@create', 'as' => 'attributes.create']);
                Route::post('attributes/create', ['uses' => 'ClientAttributeController@store', 'as' => 'attributes.store']);
                Route::get('attributes/{attribute}/edit', ['uses' => 'ClientAttributeController@edit', 'as' => 'attributes.edit']);
                Route::put('attributes/{attribute}/edit', ['uses' => 'ClientAttributeController@update', 'as' => 'attributes.update']);
                Route::get('attributes/{attribute}/delete', ['uses' => 'ClientAttributeController@delete', 'as' => 'attributes.delete']);
			});
		});

		Route::group(['prefix' => 'users'], function(){
			Route::get('/', ['uses' => 'UserController@index', 'as' => 'users']);
			Route::get('create', ['uses' => 'UserController@create', 'as' => 'users.create']);
			Route::post('create', ['uses' => 'UserController@store', 'as' => 'users.store']);
			Route::get('{user}/edit', ['uses' => 'UserController@edit', 'as' => 'users.edit']);
			Route::put('{user}/edit', ['uses' => 'UserController@update', 'as' => 'users.update']);
			Route::get('{user}/delete', ['uses' => 'UserController@delete', 'as' => 'users.delete']);
		});

		Route::group(['prefix' => 'roles'], function(){
			Route::get('/', ['uses' => 'RoleController@index', 'as' => 'roles']);
			Route::get('create', ['uses' => 'RoleController@create', 'as' => 'roles.create']);
			Route::post('create', ['uses' => 'RoleController@store', 'as' => 'roles.store']);
			Route::get('{role}/edit', ['uses' => 'RoleController@edit', 'as' => 'roles.edit']);
			Route::put('{role}/edit', ['uses' => 'RoleController@update', 'as' => 'roles.update']);
			Route::get('{role}/delete', ['uses' => 'RoleController@delete', 'as' => 'roles.delete']);
		});
	});

	/***********************************************************************************************************************************************
	 * Authenticated Routes for Client Access
	 */
	Route::group(['middleware' => 'client', 'prefix' => 'client', 'as' => 'client.', 'namespace' => 'Client'], function(){

		Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);

		Route::group(['prefix' => 'branches'], function(){
			Route::get('/', ['uses' => 'BranchController@index', 'as' => 'branches']);
			// Route::get('create', ['uses' => 'BranchController@create', 'as' => 'branches.create']); // To be remove
			// Route::post('create', ['uses' => 'BranchController@store', 'as' => 'branches.store']); // To be remove
			Route::get('{branch}/edit', ['uses' => 'BranchController@edit', 'as' => 'branches.edit']);
			Route::put('{branch}/edit', ['uses' => 'BranchController@update', 'as' => 'branches.update']);

resources/views/layouts/inc/admin-navigation.blade.php
<li class="{{ Request::is('admin') ? 'active' : '' }}"><a href="{{ route('admin.dashboard') }}"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
<li class="{{ Request::is('admin/client') || Request::is('admin/clients/*') ? 'active' : '' }}"><a href="{{ route('admin.clients') }}"><i class="fa fa-black-tie" aria-hidden="true"></i> Clients</a></li>
<li class="dropdown-trigger">
    <a href="javascript:;"><i class="fa fa-cogs"></i> Settings <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
    <ul class="dropdown">
        <li class="{{ Request::is('admin/options') || Request::is('admin/options/*') ? 'active' : '' }}"><a href="#"><i class="fa fa-cog" aria-hidden="true"></i> Options</a></li>
        <li class="{{ Request::is('admin/users') || Request::is('admin/users/*') ? 'active' : '' }}"><a href="{{ route('admin.users') }}"><i class="fa fa-user" aria-hidden="true"></i> Users</a></li>
        <li class="{{ Request::is('admin/roles') || Request::is('admin/roles/*') ? 'active' : '' }}"><a href="{{ route('admin.roles') }}"><i class="fa fa-id-card-o" aria-hidden="true"></i> Roles</a></li>
    </ul>
</li>

resources/views/layouts/inc/branch-navigation.blade.php
<li><a href="{{ route('client.dashboard') }}"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
<li class="{{ Request::is('client/branches') || Request::is('client/branches/*') ? 'active' : '' }}"><a href="{{ route('client.branches') }}"><i class="fa fa-black-tie" aria-hidden="true"></i> Branches</a></li>
<li class="dropdown-trigger">
    <a href="javascript:;"><i class="fa fa-cutlery"></i> Menu <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
    <ul class="dropdown">
        <li class="{{ Request::is('client/menus') || Request::is('client/menus/*') ? 'active' : '' }}"><a href="{{ route('client.menus') }}"><i class="fa fa-cutlery" aria-hidden="true"></i> All Menu</a></li>
        <li class="{{ Request::is('client/menus/categories') || Request::is('client/menus/categories/*') ? 'active' : '' }}"><a href="{{ route('client.menus.categories') }}"><i class="fa fa-quote-left" aria-hidden="true"></i> Categories</a></li>
    </ul>
</li>
<li class="dropdown-trigger">
    <a href="javascript:;"><i class="fa fa-shopping-basket"></i> Products <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
    <ul class="dropdown">
        <li class="{{ Request::is('client/products') || Request::is('client/products/*') ? 'active' : '' }}"><a href="{{ route('client.products') }}"><i class="fa fa-shopping-basket" aria-hidden="true"></i> All Products</a></li>
        <li class="{{ Request::is('client/product/categories') || Request::is('client/product/categories/*') ? 'active' : '' }}"><a href="{{ route('client.products.categories') }}"><i class="fa fa-quote-left" aria-hidden="true"></i> Categories</a></li>
    </ul>
</li>
<li class="dropdown-trigger">
    <a href="javascript:;"><i class="fa fa-th-list"></i> Inventory <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
    <ul class="dropdown">
        <li class="{{ Request::is('client/stock-locations') || Request::is('client/stock-locations/*') ? 'active' : '' }}"><a href="{{ route('client.stock-locations') }}"><i class="fa fa-black-tie" aria-hidden="true"></i> Stock Locations</a></li>
        <li class="{{ Request::is('client/suppliers') || Request::is('client/suppliers/*') ? 'active' : '' }}"><a href="{{ route('client.suppliers') }}"><i class="fa fa-truck" aria-hidden="true"></i> Suppliers</a></li>
    </ul>
</li>
<li class="{{ Request::is('client/customers') || Request::is('client/customers/*') ? 'active' : '' }}">
    <a href="{{ route('client.customers') }}"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Customers</a>
</li>
<li class="{{ Request::is('client/employees') || Request::is('client/employees/*') ? 'active' : '' }}">
    <a href="{{ route('client.employees') }}"><i class="fa fa-users" aria-hidden="true"></i> Employees</a>
</li>
<li class="{{ Request::is('client/options') || Request::is('client/options/*') ? 'active' : '' }}">
    <a href="javascript:;"><i class="fa fa-cogs"></i> Settings <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
</li>

resources/views/layouts/inc/client-navigation.blade.php
<li><a href="{{ route('client.dashboard') }}"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
<li class="{{ Request::is('client/branches') || Request::is('client/branches/*') ? 'active' : '' }}"><a href="{{ route('client.branches') }}"><i class="fa fa-black-tie" aria-hidden="true"></i> Branches</a></li>
<li class="dropdown-trigger">
	<a href="javascript:;"><i class="fa fa-cutlery"></i> Item <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
	<ul class="dropdown">
		<li class="{{ Request::is('client/items') || Request::is('client/items/*') ? 'active' : '' }}"><a href="{{ route('client.items') }}"><i class="fa fa-cutlery" aria-hidden="true"></i> All Items</a></li>
		<li class="{{ Request::is('client/items/categories') || Request::is('client/items/categories/*') ? 'active' : '' }}"><a href="{{ route('client.items.categories') }}"><i class="fa fa-quote-left" aria-hidden="true"></i> Categories</a></li>
	</ul>
</li>
<li class="dropdown-trigger">
	<a href="javascript:;"><i class="fa fa-th-list"></i> Inventory <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
	<ul class="dropdown">
		<li class="{{ Request::is('client/stock-locations') || Request::is('client/stock-locations/*') ? 'active' : '' }}"><a href="{{ route('client.stock-locations') }}"><i class="fa fa-black-tie" aria-hidden="true"></i> Stock Locations</a></li>
		<li class="{{ Request::is('client/stock-transfer') || Request::is('client/stock-transfer/*') ? 'active' : '' }}"><a href="{{ route('client.stock-transfer') }}"><i class="fa fa-exchange" aria-hidden="true"></i> Stock Transfer</a></li>
		<li class="{{ Request::is('client/suppliers') || Request::is('client/suppliers/*') ? 'active' : '' }}"><a href="{{ route('client.suppliers') }}"><i class="fa fa-truck" aria-hidden="true"></i> Suppliers</a></li>
	</ul>
</li>
<li class="{{ Request::is('client/customers') || Request::is('client/customers/*') ? 'active' : '' }}">
	<a href="{{ route('client.customers') }}"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Customers</a>
</li>
<li class="{{ Request::is('client/employees') || Request::is('client/employees/*') ? 'active' : '' }}">
	<a href="{{ route('client.employees') }}"><i class="fa fa-briefcase" aria-hidden="true"></i> Employees</a>
</li>
<li class="dropdown-trigger">
	<a href="javascript:;"><i class="fa fa-cogs"></i> Settings <i class="fa fa-chevron-down font-size-10 menu-dropdown-arrow"></i></a>
	<ul class="dropdown">
		<li class="{{ Request::is('client/tables') || Request::is('client/tables/*') ? 'active' : '' }}"><a href="{{ route('client.tables') }}"><i class="fa fa-th" aria-hidden="true"></i> Tables</a></li>
		<li class="{{ Request::is('client/users') || Request::is('client/users/*') ? 'active' : '' }}"><a href="{{ route('client.users') }}"><i class="fa fa-users" aria-hidden="true"></i> Users</a></li>
		<li class="{{ Request::is('client/roles') || Request::is('client/roles/*') ? 'active' : '' }}"><a href="{{ route('client.roles') }}"><i class="fa fa-users" aria-hidden="true"></i> Roles</a></li>
	</ul>
</li>

resources/views/layouts/inc/notification.blade.php
@if(session()->has('success'))
<div id="notification-show" data-type="bg-green" data-message="{{ '<i class="glyph-icon icon-check"></i>&nbsp;&nbsp;'.session('success') }}" data-layout="top"></div>
@endif

@if(session()->has('status'))
<div id="notification-show" data-type="bg-azure" data-message="{{ '<i class="glyph-icon icon-bell"></i>&nbsp;&nbsp;'.session('status') }}" data-layout="top"></div>
@endif

@if(session()->has('error'))
<div id="notification-show" data-type="bg-red" data-message="{{ '<i class="glyph-icon icon-close"></i>&nbsp;&nbsp;'.session('error') }}" data-layout="top"></div>
@endif

@if(session()->has('warning'))
<div id="notification-show" data-type="bg-orange" data-message="{{ '<i class="glyph-icon icon-exclamation"></i>&nbsp;&nbsp;'.session('warning') }}" data-layout="top"></div>
@endif